### ISSUE TITLE
Seflservice authenticated w/o 2fa?

### ISSUE THREAD

**Issue by iamohtep** [LinOTP/LinOTP#63] opened 2017-05-19 13:33 UTC
Hi !
I am currently testing LinOTP for an implementation of two-factor authentication within our small-size company (around 20 Employees). Is the two-factor authentication also supported when my Users log-in using the Selfservice portal? I have ad/ldap backend for my users and PW and tried to login using a test user-name and his password. Upon successfully authentication the password it was supposed to prompt the one-time-password token which I enrolled earlier, but didnt. Can I do two-factor when I use the selfservice?

With kind regards
Jojo

**Comment by keyidentity-mirko** [comment] 2017-05-22 14:40
Hi Jojo,

thank you for using LinOTP. At the moment the selfservice can not be protected with a second factor. However - this is a feature on our road map.

Best Regards,

Mirko

**Comment by gregharvey** [comment] 2017-10-09 13:03
Just to say +1 for this! We've starting considering rolling out 2FA with LinOTP and making it mandatory, but not being able to use LinOTP 2FA to protect the self-service GUI is a bit of a gaping back door. If you have a user's password, you can just enrol your own token! The problem with turning off self-service is, of course, then the service desk has to deal with new devices for all users, which also isn't really tenable. Hope this is coming soon! I might see if I can write a patch to achieve this anyway. :-)

**Comment by keyidentity-mirko** [comment] 2017-10-09 13:07
Hi gregharvey,

thank you for your feedback. The MFA protected self service will be part of our next major version - LinOTP 2.10 which will be released within the next weeks.

Best Regards,

Mirko

**Comment by gregharvey** [comment] 2017-10-09 13:37
Fantastic! Thanks for the quick update! :-)

**Comment by gregharvey** [comment] 2018-01-15 08:33
Hi Mirko,

Just wondering what happened to this release? Is there any way we can help? We love the product, but it seems it's struggling for resource at the moment...?

Cheers,

Greg

**Comment by keyidentity-mirko** [comment] 2018-01-15 17:16
Hi Greg,

LinOTP 2.10 with support of MFA authentication for the SelfService Portal has been released at linotp.org some minutes ago. The release for the KeyIdentity Smart Virtual Appliance will take place in the next days.

The changelog can be found here: https://www.linotp.org/resources/changelogs.html

Configuration details about MFA are documented here: https://www.linotp.org/doc/latest/part-management/policy/selfservice.html#  (have a look for actions mfa_login and mfa_3_fields).

As usual - your feedback is highly appreciated.

Best Regards,

Mirko

**Comment by gregharvey** [comment] 2018-01-16 11:40
Fantastic, thanks Mirko! :-)

**Comment by gregharvey** [comment] 2018-02-05 13:37
Just a quick note to say this works really well and I think this issue can be closed! :-)

Thanks again!

**Comment by flippipe** [comment] 2021-01-27 12:45
Hi @keyidentity-mirko,

MFA in SelfService supports tokens like SMS or Email?

**Comment by lukengda** [comment] 2021-01-27 15:09
Yes, LinOTP supports all token types for the MFA login to the Selfservice portal. The issue is done, closing hereby!

**Closed by lukengda** 2021-01-27 15:09 UTC
