### ISSUE TITLE
'wrong otp value' for some TOTP tokens

### ISSUE THREAD

**Issue by Jess103** [LinOTP/LinOTP#151] opened 2020-10-20 01:40 UTC
**UPDATE (201021)**
(I just copied my comment on the bottom here so that it's easy to read)

Just in case right now I tested few more with digits changing too, and found out that
**the ones I created with**
**1. 8digits + 60sec ☞ all conditions work** (8digits+60sec, 6digits+30sec/60sec)
**2. 6digits + 60sec ☞ only 6digits work** (30sec/60sec)
**3. 6digits + 30sec ☞ only 6digits 30sec work**
* my app can only produce the tokens with 8d+60s, 6d+30s, and 6d60s that I could not test 8d+30s; but the pattern looks like changing to lower digits/timestep always works that the first token pretty sure will work with 8d30s as well.

I want to know if this only applies when I create tokens on my server or applies the same for the ones I create on /manage page, but I get empty User View on the page that I cannot check... (Even thought there are users on the db that I assign the token when I create it via /admin/init) I would really appreciate if somebody else can check it for me...

----------

(201020)

Hi,

I've been changing the TokenInfo settings (digits and timesteps only) via the /manage page and found out that some tokens still work but some tokens don't...

[*all tokens have NO PINs]
- For example, I have a **token A** as **sha256, 30sec, 6digits** ☞ successfully authenticated
- I change it to **sha256, 60sec, 6digits** ☞ successfully authenticaed
- And now I have a **token B** with the settings of **sha256, 30sec, 6 digits** ☞successfully authenticaed
- I change it to **sha256, 60sec, 6 digits** ☞ WRONG OTP VALUE

I created token C and D to test more and found out that C works well in all conditions like A, but D doesn't work when it's 60sec.

30sec always works fine but 60sec... I have no idea what's going on

How can this happen? 
I'm so confused...

The secret is still the same (that it works when I change the setting back to 30sec), and I reset the fail counter before it hits 10.

**Comment by megfault** [comment] 2020-10-20 08:51
Hi @Jess103 I am trying to reproduce the issue. Did you also change the time step from 30 to 60 on the application generating the OTPs?

**Comment by Jess103** [comment] 2020-10-20 09:30
Hi @megfault ! Thanks for the comment.

I created the tokens via java (/admin/init) with settings of sha256 and 6digits.
It uses the default timestep, which I changed to 60 on /manage page (Linotp Config > Token Config > TOTP)

**Comment by megfault** [comment] 2020-10-20 19:29
Sure, but where are you generating the OTPs? Did you also change the timestep there afterwards?

**Comment by Jess103** [comment] 2020-10-20 22:11
On my server, I changed some of the 60sec ones to 30sec (☞this works). Then I tried changing it back to 60sec via /manage, via LinOTP db, and via my server again, but all did not work... 
I mean I can see that token settings are changed in db (TokenInfo part of the Token table), but the I get the "worng otp value" response. Again, it's really weird cuz it works again when I change the setting back to 30sec(no matter where I change this setting), and the other token works perfectly fine in all different conditions...
What am I missing here??? I'm so lost......

**Comment by megfault** [comment] 2020-10-20 22:45
I think you did not understand my question.

You have a LinOTP instance. That's where you create the TOTP token, either via the /admin/init or the management UI, it does not matter. When you create the token, you usually receive a configuration string or a QR code representing the string. The configuration must be imported by some client (most people will use a mobile app, I assume, to scan the QR code). That client can then generate the OTP based on the configuration.

After you change the configuration (e.g. time step) on your server, it must also be changed on your client, otherwise it will not work. It _should_ not work, and if it indeed does sometimes, we must look into it. So please tell me what client you are using to generate OTPs, and whether you also changed the configuration there afterwards.

**Comment by Jess103** [comment] 2020-10-20 22:49
Ok so you wanted to know if I've been changing the client side settings as well, correct?
I use my own app and of course every time I change the settings on server, I generate new QR to scan again. And this is why I've been keep saying that other token works in both 30sec n 60sec conditions.

**Comment by megfault** [comment] 2020-10-20 22:51
Ok, that's interesting. Mind sharing the seeds of said tokens?

**Comment by megfault** [comment] 2020-10-20 22:57
Oh, one more thing. It's not clear whether you changed the config of an already created token (that's what I understood from your first post) or the global TOTP token config (seems to be the case in your second post) or both. I suspect that changing the global TOTP config only affects tokens created after that, but I will have to look up documentation and/or code to confirm it.

**Comment by Jess103** [comment] 2020-10-20 23:07
1. Seed
I'm outside rn that I'll share it after I get back.
You mean the seed not the secret which is in the 'otpauth://....' right?

2. Settings
I changed the token itself setting, not the global one!
You are correct that when you change the global settings only the ones created afterwards are affected

**Comment by megfault** [comment] 2020-10-20 23:23
Yes, I mean the seeds. The rest should be deterministic. But no need to hurry. I will try to reproduce your setup first and if I find strange behavior already I will not need the seeds at all.

 Please confirm then if this is correct:
1. First of all, your global TOTP timestep was set to 60 as a default and you never changed it there again.
2. Then you created, tested and reconfigured the tokens as specified in your first post.

**Comment by Jess103** [comment] 2020-10-20 23:29
Token A (both 30sec, 60sec work)
seed://4d485246474d4959394553424255354d494d5557
 
Token B(ONLY 30sec works)
seed://30524e4d39393541384f3446505249385a435a38


Yes, both correct.
1. I never touched the global settings when I was testing with theses tokens.
2. I tried changing the token itself settings on manage page / LINOTP db / on my server and again, Token A works fine no matter where I change the setting while Token B never works with 60 sec condition.

**Comment by Jess103** [comment] 2020-10-21 05:11
I tested more tokens today and it seems like if I change timestep on my server, it 'sticks' to that setting that even when I change the settings it's not truly applied...
Whenever I create a token w/o changing the timestep, it works fine in both 30 and 60 conditions.

Just in case right now I tested few more with digits changing too, and found out that the ones I created with
1. 8digits + 60sec ☞ all conditions work
2. 6digits + 60sec ☞ only 6digits(30sec/60sec) work
3. 6digits + 30sec ☞ only 6digits 30sec work

**Comment by xt-kay** [comment] 2020-10-21 09:30
Hi,
please be aware, that changing the hashlib is more than changing the hash algorithm:
a sha1 requires a 20 bytes seed, a sha256 at least 32 bytes. Switching the algorithm
does not guarantee, how the missing bytes are filled up

**Comment by Jess103** [comment] 2020-10-21 09:49
Hi @xt-kay 
I'm not really sure which one are you talking about.
I never changed the algorithm during this test; I only changed the timestep and digits only

**Comment by megfault** [comment] 2020-10-23 15:04
Hi @Jess103, this is just to let you know that we haven't forgotten about this issue.  We'll report back once we know more.

**Comment by xt-kay** [comment] 2020-10-27 13:11
Hi @Jess103,
can you please explain to me, what are the exact steps that you try to verify that linotp does it wrong:
- are you using your generated otps and check them against linotp with a 'validate/check'?
or are you using someting different?

**Comment by Jess103** [comment] 2020-10-27 16:01
Hi @xt-kay 
1) I have a mobile app which can produce 3 different case tokens: SHA256+6digits+30sec / SHA256+6digits+60sec / SHA256+8digits+60sec.
2) I generated and assigned otp tokens to test accounts via '/admin/init'.
3) To check the otp values, I used 'validate/check'.
4) To change the token settings, I selected the token I want and clicked 'TokenInfo' on '/manage' page.
Does this answer your question? If you need more explanation please let me know!

**Comment by lukengda** [comment] 2021-06-10 15:40
There was a problem were the replay attack prevention counter was not re-calulated when the time step was changed (this is necessary because the counter changes based on the time step). This is fixed in master since November 2020.

This is the only problem I could identify based on your issue description. I can change an existing token in the Manage-UI from 6 to 8 to 6 digits and from 30 to 60 to 30 seconds time period and it keeps working. I will therefore close the issue for the moment. Feel free to report back if you have another issue.

**Closed by lukengda** 2021-06-10 15:40 UTC
